# syntax = edrevo/dockerfile-plus
INCLUDE+ Dockerfile.base
RUN wget -qP /tmp/ https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-amd64.tar.gz \
    && tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && rm /tmp/s6-overlay-amd64.tar.gz

ENTRYPOINT ["/init"]