version: '3.9'

services:
  aki-php:
    container_name: akiPhp
    build:
      context: ../.
      dockerfile: Dockerfile.dev
    volumes:
      - ../../:/var/www
      - ../s6script/cont-init.d:/etc/cont-init.d
      - ../s6script/cont-finish.d:/etc/cont-finish.d
    ports:
      - 8180:8080
      - 3100:3000

  aki-nginx:
    image: nginx:latest
    container_name: aki-nginx
    ports:
      - 8880:8000
    volumes:
      - ../../:/var/www
      - ../Configs/Dev/nginx.conf:/etc/nginx/conf.d/default.conf

  aki-postgres:
    image: library/postgres:10.14
    container_name: aki-postgres
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 54320:5432
    volumes:
      - ../db-dumps:/var/db-dumps
      - aki_postgres_data10:/var/lib/postgresql/data10

volumes:
  aki_postgres_data10: {}

  #measure-redis:
    #container_name: measure-redis
    #image: redis:alpine
    #ports:
      #- 16379:6379