version: '3.9'

services:
  workspace-php:
    container_name: workspace-php
    build:
      context: ../.
      dockerfile: Dockerfile.dev
    volumes:
      - ../../:/var/www
      - ../s6script/cont-init.d:/etc/cont-init.d
      - ../s6script/cont-finish.d:/etc/cont-finish.d
    ports:
      - 8280:8080
      - 3200:3000

  workspace-nginx:
    image: nginx:latest
    container_name: workspace-nginx
    ports:
      - 8880:8000
      - 442:443
    volumes:
      - ../../:/var/www
      - ../../certs:/etc/nginx/certs
      - ../Configs/Dev/nginx.conf:/etc/nginx/conf.d/default.conf

  workspace-postgres:
    image: library/postgres:10.14
    container_name: workspace-postgres
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 54322:5432
    volumes:
      - ../db-dumps:/var/db-dumps
      - workspace_postgres_data10:/var/lib/postgresql/data10

volumes:
  workspace_postgres_data10: {}

  #measure-redis:
    #container_name: measure-redis
    #image: redis:alpine
    #ports:
      #- 16379:6379